-- ==============================================================================
-- VIBE-FASHION 쇼핑몰 데이터베이스 스키마
-- Supabase SQL Editor에서 전체 실행 가능
-- ==============================================================================

-- 1. 확장 기능 활성화
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 2. 테이블 생성
-- ==============================================================================

-- (1) profiles: 회원 프로필 (auth.users 연동)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    avatar_url TEXT,
    phone TEXT,
    grade TEXT NOT NULL DEFAULT 'BRONZE' CHECK (grade IN ('BRONZE', 'SILVER', 'GOLD', 'VIP')),
    total_spent BIGINT NOT NULL DEFAULT 0 CHECK (total_spent >= 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    points BIGINT NOT NULL DEFAULT 0 CHECK (points >= 0),
    admin_memo TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'suspended')),
    ADD COLUMN IF NOT EXISTS points BIGINT NOT NULL DEFAULT 0 CHECK (points >= 0),
    ADD COLUMN IF NOT EXISTS admin_memo TEXT NOT NULL DEFAULT '';

-- (2) categories: 상품 카테고리
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- (3) products: 상품 기본 정보
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    slug TEXT UNIQUE,
    description TEXT,
    price INT NOT NULL CHECK (price >= 0),
    sale_price INT CHECK (sale_price >= 0 AND sale_price <= price),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- (4) product_options: 상품 옵션 및 재고
CREATE TABLE IF NOT EXISTS public.product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    color TEXT,
    size TEXT,
    extra_price INT NOT NULL DEFAULT 0,
    stock_quantity INT NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    safe_stock INT NOT NULL DEFAULT 5 CHECK (safe_stock >= 0),
    sku TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.product_options
    ADD COLUMN IF NOT EXISTS safe_stock INT NOT NULL DEFAULT 5 CHECK (safe_stock >= 0);

-- (5) product_images: 상품 이미지
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_thumbnail BOOLEAN NOT NULL DEFAULT false,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- (6) carts: 장바구니
CREATE TABLE IF NOT EXISTS public.carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    option_id BIGINT REFERENCES public.product_options(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT unique_user_product_option UNIQUE NULLS NOT DISTINCT (user_id, product_id, option_id)
);

-- (7) orders: 주문 내역
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'pending' 
        CHECK (status IN ('pending', 'paid', 'preparing', 'shipping', 'delivered', 'cancelled', 'refunded')),
    total_amount INT NOT NULL CHECK (total_amount >= 0),
    discount_amount INT NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    shipping_fee INT NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
    final_amount INT NOT NULL CHECK (final_amount >= 0),
    recipient_name TEXT NOT NULL,
    recipient_phone TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    shipping_memo TEXT,
    payment_method TEXT,
    payment_key TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- (8) order_items: 주문 상품 상세
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    option_id BIGINT REFERENCES public.product_options(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    option_info TEXT,
    price INT NOT NULL CHECK (price >= 0),
    quantity INT NOT NULL CHECK (quantity > 0),
    subtotal INT NOT NULL CHECK (subtotal >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- (9) refunds: 환불 요청 및 관리
CREATE TABLE IF NOT EXISTS public.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    order_item_id BIGINT REFERENCES public.order_items(id) ON DELETE SET NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'requested' 
        CHECK (status IN ('requested', 'approved', 'rejected', 'completed')),
    request_type TEXT NOT NULL DEFAULT 'return' CHECK (request_type IN ('return', 'exchange')),
    reason TEXT NOT NULL,
    customer_request TEXT NOT NULL DEFAULT '',
    requested_option TEXT,
    requested_option_id BIGINT REFERENCES public.product_options(id) ON DELETE SET NULL,
    refund_amount INT NOT NULL CHECK (refund_amount >= 0),
    collection_status TEXT NOT NULL DEFAULT 'pending' CHECK (collection_status IN ('pending', 'completed')),
    inspection_status TEXT NOT NULL DEFAULT 'pending' CHECK (inspection_status IN ('pending', 'completed')),
    refund_status TEXT NOT NULL DEFAULT 'pending' CHECK (refund_status IN ('pending', 'completed')),
    redelivery_status TEXT NOT NULL DEFAULT 'pending' CHECK (redelivery_status IN ('pending', 'shipped')),
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.refunds
    ADD COLUMN IF NOT EXISTS request_type TEXT NOT NULL DEFAULT 'return'
        CHECK (request_type IN ('return', 'exchange')),
    ADD COLUMN IF NOT EXISTS customer_request TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS requested_option TEXT,
    ADD COLUMN IF NOT EXISTS requested_option_id BIGINT REFERENCES public.product_options(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS collection_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (collection_status IN ('pending', 'completed')),
    ADD COLUMN IF NOT EXISTS inspection_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (inspection_status IN ('pending', 'completed')),
    ADD COLUMN IF NOT EXISTS refund_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (refund_status IN ('pending', 'completed')),
    ADD COLUMN IF NOT EXISTS redelivery_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (redelivery_status IN ('pending', 'shipped'));

CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    option_id BIGINT REFERENCES public.product_options(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
    order_item_id BIGINT REFERENCES public.order_items(id) ON DELETE SET NULL,
    refund_id BIGINT REFERENCES public.refunds(id) ON DELETE SET NULL,
    movement_type TEXT NOT NULL CHECK (movement_type IN ('order', 'cancel_restock', 'return_restock', 'exchange_restock', 'exchange_out', 'adjustment')),
    quantity INT NOT NULL CHECK (quantity <> 0),
    reason TEXT NOT NULL DEFAULT '',
    event_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS inventory_movements_option_date_idx
    ON public.inventory_movements(option_id, created_at DESC);
CREATE INDEX IF NOT EXISTS inventory_movements_product_date_idx
    ON public.inventory_movements(product_id, created_at DESC);

-- (10) notifications: 회원 알림
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'order',
    link_url TEXT,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- (11) reviews: 상품 리뷰
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    order_item_id BIGINT REFERENCES public.order_items(id) ON DELETE SET NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- 3. 자동 갱신 및 트리거 함수 정의
-- ==============================================================================

-- (1) updated_at 타임스탬프 자동 갱신 함수
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- updated_at 트리거 부착
CREATE OR REPLACE TRIGGER set_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER set_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER set_carts_updated_at
    BEFORE UPDATE ON public.carts
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER set_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER set_refunds_updated_at
    BEFORE UPDATE ON public.refunds
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER set_reviews_updated_at
    BEFORE UPDATE ON public.reviews
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- (2) auth.users 신규 생성 시 profiles 자동 생성 트리거 (소셜 로그인 포함)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    extracted_name TEXT;
    extracted_avatar TEXT;
BEGIN
    -- 소셜 로그인(Google, Kakao, Github 등) 및 이메일 회원가입 메타데이터 파싱
    extracted_name := COALESCE(
        NEW.raw_user_meta_data->>'full_name',
        NEW.raw_user_meta_data->>'name',
        NEW.raw_user_meta_data->>'user_name',
        split_part(NEW.email, '@', 1)
    );

    extracted_avatar := COALESCE(
        NEW.raw_user_meta_data->>'avatar_url',
        NEW.raw_user_meta_data->>'picture',
        ''
    );

    INSERT INTO public.profiles (
        id,
        email,
        full_name,
        avatar_url,
        grade,
        total_spent,
        role
    ) VALUES (
        NEW.id,
        NEW.email,
        extracted_name,
        extracted_avatar,
        'BRONZE',
        0,
        'customer'
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        full_name = COALESCE(public.profiles.full_name, EXCLUDED.full_name),
        avatar_url = COALESCE(public.profiles.avatar_url, EXCLUDED.avatar_url);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- auth.users에 트리거 등록
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- (3) 고객 등급 자동 업데이트 함수 (누적 실 결제금액 기준)
-- 기준: VIP(100만원 이상), GOLD(30만원 이상), SILVER(10만원 이상), BRONZE(기본)
CREATE OR REPLACE FUNCTION public.update_customer_grade(target_user_id UUID)
RETURNS VOID AS $$
DECLARE
    spent_sum BIGINT := 0;
    new_grade TEXT := 'BRONZE';
BEGIN
    IF target_user_id IS NULL THEN
        RETURN;
    END IF;

    -- 결제 완료/배송/배송완료 상태인 주문의 총 실결제 금액 합산 (취소/환불 제외)
    SELECT COALESCE(SUM(final_amount), 0)
    INTO spent_sum
    FROM public.orders
    WHERE user_id = target_user_id
      AND status IN ('paid', 'preparing', 'shipping', 'delivered');

    -- 환불 완료된 금액 차감
    spent_sum := spent_sum - COALESCE((
        SELECT SUM(refund_amount)
        FROM public.refunds
        WHERE user_id = target_user_id
          AND status = 'completed'
    ), 0);

    IF spent_sum < 0 THEN
        spent_sum := 0;
    END IF;

    -- 등급 산정
    IF spent_sum >= 1000000 THEN
        new_grade := 'VIP';
    ELSIF spent_sum >= 300000 THEN
        new_grade := 'GOLD';
    ELSIF spent_sum >= 100000 THEN
        new_grade := 'SILVER';
    ELSE
        new_grade := 'BRONZE';
    END IF;

    -- 프로필 테이블 갱신
    UPDATE public.profiles
    SET total_spent = spent_sum,
        grade = new_grade,
        updated_at = timezone('utc'::text, now())
    WHERE id = target_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- (4) 주문 및 환불 상태 변경 시 고객 등급 자동 갱신 트리거 함수
CREATE OR REPLACE FUNCTION public.trigger_customer_grade_sync()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_TABLE_NAME = 'orders' THEN
        -- 주문 유저 등급 갱신
        IF NEW.user_id IS NOT NULL THEN
            PERFORM public.update_customer_grade(NEW.user_id);
        END IF;
        IF OLD.user_id IS NOT NULL AND OLD.user_id <> NEW.user_id THEN
            PERFORM public.update_customer_grade(OLD.user_id);
        END IF;
    ELSIF TG_TABLE_NAME = 'refunds' THEN
        -- 환불 관련 유저 등급 갱신
        IF NEW.user_id IS NOT NULL THEN
            PERFORM public.update_customer_grade(NEW.user_id);
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.apply_order_item_inventory()
RETURNS TRIGGER AS $$
DECLARE
    product_option_product_id BIGINT;
BEGIN
    IF NEW.option_id IS NULL THEN
        RETURN NEW;
    END IF;

    UPDATE public.product_options
    SET stock_quantity = stock_quantity - NEW.quantity
    WHERE id = NEW.option_id
      AND stock_quantity >= NEW.quantity
    RETURNING product_id INTO product_option_product_id;

    IF product_option_product_id IS NULL THEN
        RAISE EXCEPTION '상품 재고가 부족하거나 옵션을 찾을 수 없습니다.';
    END IF;

    INSERT INTO public.inventory_movements (
        product_id, option_id, order_id, order_item_id, movement_type, quantity, reason, event_key
    ) VALUES (
        product_option_product_id, NEW.option_id, NEW.order_id, NEW.id, 'order', -NEW.quantity,
        '주문 출고', 'order-item:' || NEW.id::TEXT
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.restore_cancelled_order_inventory()
RETURNS TRIGGER AS $$
DECLARE
    order_line RECORD;
BEGIN
    IF NEW.status = 'cancelled' AND OLD.status IN ('pending', 'paid', 'preparing') THEN
        FOR order_line IN
            SELECT id, product_id, option_id, quantity
            FROM public.order_items
            WHERE order_id = NEW.id AND option_id IS NOT NULL
        LOOP
            UPDATE public.product_options
            SET stock_quantity = stock_quantity + order_line.quantity
            WHERE id = order_line.option_id;

            INSERT INTO public.inventory_movements (
                product_id, option_id, order_id, order_item_id, movement_type, quantity, reason, event_key
            ) VALUES (
                order_line.product_id, order_line.option_id, NEW.id, order_line.id, 'cancel_restock',
                order_line.quantity, '주문 취소 재입고', 'cancel-order-item:' || order_line.id::TEXT
            ) ON CONFLICT (event_key) DO NOTHING;
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.apply_return_inventory()
RETURNS TRIGGER AS $$
DECLARE
    order_line RECORD;
    target_product_id BIGINT;
BEGIN
    IF NEW.status <> 'approved' THEN
        RETURN NEW;
    END IF;

    IF NEW.inspection_status = 'completed' AND OLD.inspection_status <> 'completed' THEN
        FOR order_line IN
            SELECT id, product_id, option_id, quantity
            FROM public.order_items
            WHERE order_id = NEW.order_id
              AND option_id IS NOT NULL
              AND (NEW.order_item_id IS NULL OR id = NEW.order_item_id)
        LOOP
            UPDATE public.product_options
            SET stock_quantity = stock_quantity + order_line.quantity
            WHERE id = order_line.option_id;

            INSERT INTO public.inventory_movements (
                product_id, option_id, order_id, order_item_id, refund_id, movement_type, quantity, reason, event_key
            ) VALUES (
                order_line.product_id, order_line.option_id, NEW.order_id, order_line.id, NEW.id,
                CASE WHEN NEW.request_type = 'exchange' THEN 'exchange_restock' ELSE 'return_restock' END,
                order_line.quantity, '반품 상품 검수 후 입고', 'return-restock:' || NEW.id::TEXT || ':' || order_line.id::TEXT
            ) ON CONFLICT (event_key) DO NOTHING;
        END LOOP;
    END IF;

    IF NEW.request_type = 'exchange'
       AND NEW.redelivery_status = 'shipped'
       AND OLD.redelivery_status <> 'shipped' THEN
        IF NEW.requested_option_id IS NULL THEN
            RAISE EXCEPTION '재배송할 교환 옵션을 선택해 주세요.';
        END IF;

        UPDATE public.product_options
        SET stock_quantity = stock_quantity - 1
        WHERE id = NEW.requested_option_id
          AND stock_quantity > 0
        RETURNING product_id INTO target_product_id;

        IF target_product_id IS NULL THEN
            RAISE EXCEPTION '교환 상품 재고가 부족합니다.';
        END IF;

        INSERT INTO public.inventory_movements (
            product_id, option_id, order_id, refund_id, movement_type, quantity, reason, event_key
        ) VALUES (
            target_product_id, NEW.requested_option_id, NEW.order_id, NEW.id, 'exchange_out', -1,
            '교환 상품 재배송', 'exchange-out:' || NEW.id::TEXT
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.adjust_inventory(
    target_option_id BIGINT,
    quantity_delta INT,
    adjustment_reason TEXT,
    movement_event_key TEXT
)
RETURNS JSONB AS $$
DECLARE
    target_product_id BIGINT;
    updated_option JSONB;
BEGIN
    IF quantity_delta = 0 THEN
        RAISE EXCEPTION '재고 변경 수량은 0일 수 없습니다.';
    END IF;

    UPDATE public.product_options
    SET stock_quantity = stock_quantity + quantity_delta
    WHERE id = target_option_id
      AND stock_quantity + quantity_delta >= 0
    RETURNING product_id, to_jsonb(product_options) INTO target_product_id, updated_option;

    IF target_product_id IS NULL THEN
        RAISE EXCEPTION '재고가 부족하거나 옵션을 찾을 수 없습니다.';
    END IF;

    INSERT INTO public.inventory_movements (
        product_id, option_id, movement_type, quantity, reason, event_key
    ) VALUES (
        target_product_id, target_option_id, 'adjustment', quantity_delta,
        COALESCE(adjustment_reason, ''), movement_event_key
    );
    RETURN updated_option;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

REVOKE ALL ON FUNCTION public.adjust_inventory(BIGINT, INT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.adjust_inventory(BIGINT, INT, TEXT, TEXT) TO service_role;

-- orders 및 refunds 테이블에 등급 갱신 트리거 부착
CREATE OR REPLACE TRIGGER sync_grade_on_order_change
    AFTER INSERT OR UPDATE OF status, final_amount, user_id ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.trigger_customer_grade_sync();

CREATE OR REPLACE TRIGGER sync_grade_on_refund_change
    AFTER INSERT OR UPDATE OF status, refund_amount, user_id ON public.refunds
    FOR EACH ROW EXECUTE FUNCTION public.trigger_customer_grade_sync();

DROP TRIGGER IF EXISTS order_item_inventory_after_insert ON public.order_items;
CREATE TRIGGER order_item_inventory_after_insert
    AFTER INSERT ON public.order_items
    FOR EACH ROW EXECUTE FUNCTION public.apply_order_item_inventory();

DROP TRIGGER IF EXISTS order_cancel_inventory_after_update ON public.orders;
CREATE TRIGGER order_cancel_inventory_after_update
    AFTER UPDATE OF status ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.restore_cancelled_order_inventory();

DROP TRIGGER IF EXISTS return_inventory_after_update ON public.refunds;
CREATE TRIGGER return_inventory_after_update
    AFTER UPDATE OF inspection_status, redelivery_status ON public.refunds
    FOR EACH ROW EXECUTE FUNCTION public.apply_return_inventory();

-- ==============================================================================
-- 4. RLS (Row Level Security) 설정 및 기본 정책
-- ==============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 1) profiles 정책: 본인 프로필 조회/수정 가능, 전체 공개 프로필 조회 허용
CREATE POLICY "프로필 조회는 모든 사용자 가능" 
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "본인 프로필만 수정 가능" 
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2) categories, products, product_options, product_images: 모든 사용자 조회 가능
CREATE POLICY "카테고리 누구나 조회 가능" 
    ON public.categories FOR SELECT USING (true);

CREATE POLICY "상품 정보 누구나 조회 가능" 
    ON public.products FOR SELECT USING (is_active = true);

CREATE POLICY "상품 옵션 누구나 조회 가능" 
    ON public.product_options FOR SELECT USING (true);

CREATE POLICY "상품 이미지 누구나 조회 가능" 
    ON public.product_images FOR SELECT USING (true);

-- 3) carts: 본인 장바구니만 CRUD 가능
CREATE POLICY "본인 장바구니만 접근 가능" 
    ON public.carts FOR ALL USING (auth.uid() = user_id);

-- 4) orders & order_items: 본인 주문만 조회/생성 가능
CREATE POLICY "본인 주문만 조회 가능" 
    ON public.orders FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "본인 주문만 생성 가능" 
    ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "본인 주문 상세만 조회 가능" 
    ON public.order_items FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.orders 
            WHERE orders.id = order_items.order_id 
              AND orders.user_id = auth.uid()
        )
    );

-- 5) refunds: 본인 환불 요청만 조회/생성 가능
CREATE POLICY "본인 환불 내역 조회 가능" 
    ON public.refunds FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "본인 환불 요청 생성 가능" 
    ON public.refunds FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6) notifications: 본인 알림만 조회/수정(읽음 처리) 가능
CREATE POLICY "본인 알림만 접근 가능" 
    ON public.notifications FOR ALL USING (auth.uid() = user_id);

-- 7) reviews: 누구나 조회 가능, 작성/수정/삭제는 본인만 가능
CREATE POLICY "리뷰 누구나 조회 가능" 
    ON public.reviews FOR SELECT USING (true);

CREATE POLICY "본인 리뷰만 등록 가능" 
    ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "본인 리뷰만 수정/삭제 가능" 
    ON public.reviews FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "본인 리뷰만 삭제 가능" 
    ON public.reviews FOR DELETE USING (auth.uid() = user_id);
